from .http import jitter_sleep, make_curl_session, request_with_retry
from .db import (
    get_conn,
    release_conn,
    init_db,
    insert_many,
    start_run,
    finish_run,
    log_failed_query,
    get_failed_queries,
    last_successful_run,
    find_active_deals,
    cheapest_per_retailer,
    cheapest_per_retailer_standard,
    price_history,
    lowest_price_ever,
    find_by_upc,
    get_all_retailers,
    get_store_status,
    get_price_history_by_name,
    get_db_stats,
    get_dashboard_summary,
    get_market_pulse,
    get_scrape_activity,
    get_departments,
    get_department_products,
    get_price_trend,
    get_store_analytics,
    get_data_freshness,
    get_watchlist_prices,
    cleanup_old_prices,
    add_watchlist_item,
    remove_watchlist_item,
    get_watchlist,
    check_price_alerts,
    get_active_alerts,
    acknowledge_alert,
    get_scraper_stats,
)
from .compare import (
    compare_by_name,
    compare_by_unit_price,
    find_deals,
    find_text_deals,
    best_price_per_retailer,
    print_unit_price_comparison,
)
from .unit_price import normalize_unit_price, parse_size, format_unit_price, compute_standard_unit_price
from .category_resolver import resolve_standard_unit
from .validate import validate_results, check_count_drop

__all__ = [
    # HTTP
    "jitter_sleep",
    "make_curl_session",
    "request_with_retry",
    # Database
    "get_conn",
    "release_conn",
    "init_db",
    "insert_many",
    "start_run",
    "finish_run",
    "log_failed_query",
    "get_failed_queries",
    "last_successful_run",
    "find_active_deals",
    "cheapest_per_retailer",
    "cheapest_per_retailer_standard",
    "price_history",
    "lowest_price_ever",
    "find_by_upc",
    "get_all_retailers",
    "get_store_status",
    "get_price_history_by_name",
    "get_db_stats",
    "get_dashboard_summary",
    "get_market_pulse",
    "get_scrape_activity",
    "get_departments",
    "get_department_products",
    "get_price_trend",
    "get_store_analytics",
    "get_data_freshness",
    "get_watchlist_prices",
    "cleanup_old_prices",
    # Watchlist & price alerts
    "add_watchlist_item",
    "remove_watchlist_item",
    "get_watchlist",
    "check_price_alerts",
    "get_active_alerts",
    "acknowledge_alert",
    "get_scraper_stats",
    # In-memory comparison (for reporting on current-run results)
    "compare_by_name",
    "compare_by_unit_price",
    "find_deals",
    "find_text_deals",
    "best_price_per_retailer",
    "print_unit_price_comparison",
    # Unit price normalization
    "normalize_unit_price",
    "parse_size",
    "format_unit_price",
    # Category-aware standard pricing
    "compute_standard_unit_price",
    "resolve_standard_unit",
    # Data quality validation
    "validate_results",
    "check_count_drop",
]
